# Site settings

title: Maria Menendez-Pino
email: M.menendezpino@gmail.com
url: https://www.linkedin.com/in/maria-menendez
description: "Portfolio of cybersecurity work samples for a junior-level cyber security professional."
keywords: "cybersecurity, cyber, security, portfolio, tech"
skills: "Cybersecurity - Analyst - Ethical Hacker"
meta_author: Maria Menendez-Pino

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
#Â - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: 

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 800080 # A deep purple
  primary-rgb: "128,0,128" # A deep purple
  secondary: 9370DB # Medium purple
  secondary-dark: 4B0082 # Indigo

# Footer settings
footer:
  copyright: Maria Menendez- Pino
  location: Location
  social: Around the Web
  credits: Credits

# Social network usernames (many more available: google-plus, Flickr, dribble, Pinterest, Instagram, Tumblr, LinkedIn, etc.)
social:
  - title: Linkedin
    url: www.linkedin.com/in/maria-menendez-pino
  - title: GitHub
    url: https://github.com/lilmaria10

# Email Address (make sure to include "mailto:" before your email!)
email:
  email-url: mailto:m.menendezpino@gmail.com

# Postal address (add as many lines as necessary)
location:
  - line: Mooresville, NC 

# for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
